[package]
name = "bevy_immediate"
version = "0.1.0"
edition = "2024"
authors = ["Pēteris Pakalns"]
repository = "https://github.com/PPakalns/bevy_immediate/"
homepage = "https://github.com/PPakalns/bevy_immediate/"
description = ""
keywords = ["bevy", "ui", "immediate", "simple", "ecs"]
categories = ["gui", "graphics", "ui"]
license = "MIT"
rust-version = "1.85"
exclude = ["/.github", "./examples/web/"]
autoexamples = false

[dependencies]
bevy_ecs = "0.16"
bevy_ui = { version = "0.16", optional = true }
bevy_app = "0.16"
bevy_platform = "0.16"
bevy_picking = { version = "0.16", optional = true }
bevy_derive = "0.16"
bevy_internal = { version = "0.16", default-features = false }

log = "0.4"
ahash = "0.8"
type-map = "0.5"
paste = "1.0"

[features]
default = ["ui", "picking"]

ui = ["dep:bevy_ui"]
picking = [
  "ui",
  "dep:bevy_picking",
  "bevy_internal/bevy_picking",
  "bevy_internal/bevy_ui_picking_backend",
]

[dev-dependencies]
bevy = { version = "0.16", default-features = false, features = [
  "bevy_ui",
  "bevy_ui_debug",
  "bevy_log",
  "bevy_window",
  "bevy_winit",
  "webgl2",
  "x11",
  "wayland",
  "bevy_text",
  "default_font",
  "bevy_picking",
] }


[[example]]
name = "demo"
